version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  yamdb:
    image: admin/yamdb:latest
    restart: always
    volumes:
      - ./static_volume:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.4
    volumes:
      - ./static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - yamdb