# Generated by Django 3.0.5 on 2020-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200926_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='LTKA66YJVZ', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
